name: Harbortouch
favicon: null
layout_spectrum: 0.50177
typography_spectrum: 0.72006
title: Harbortouch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#00ffff'
    - '#3b3b3b'
    - '#9f9f9f'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
