typography_spectrum: 0.66601
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#00ffff'
    - '#3b3b3b'
    - '#9f9f9f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24772
analytics:
  google: null
  facebook: null
  twitter: null
name: Harbortouch Echo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Harbortouch
purpose: []
